### ISSUE TITLE
Application 

### ISSUE THREAD

**Issue by DavidModzz** [favolia/skytopia-rot#1]
I really liked your work and I would like to translate this project into Spanish, it will only be for my personal use

**Comment by favolia** [comment]
Of course, but it's not mine, it officially belongs to ROT-Utilities,
this is their github

https://github.com/ROT-Utilities

**Comment by DavidModzz** [comment]
> Of course, but it's not mine, it officially belongs to ROT-Utilities,
> this is their github
> 
> https://github.com/ROT-Utilities

Could you explain to me how to install?I add it as a behavior package and it doesn't work for me

**Comment by DavidModzz** [comment]
> Of course, but it's not mine, it officially belongs to ROT-Utilities,
> this is their github
> 
> https://github.com/ROT-Utilities

Could you explain to me how to install?I add it as a behavior package and it doesn't work for me

**Comment by favolia** [comment]
maybe you should install the resource pack

here is the resource pack:
https://github.com/ROT-Utilities/ROT-RP
